[package]
name = "rill-engine"
version = "0.35.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rillrate/rillrate-rs"
homepage = "https://github.com/rillrate/rillrate-rs"
documentation = "https://docs.rs/rill-engine/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["logging"]
categories = ["development-tools::debugging"]
description = "Dynamic logging and tracing system"

[dependencies]
anyhow = "1.0.42"
async-trait = "0.1.50"
derive_more = "0.99.16"
futures = "0.3.15"
log = "0.4.14"
meio = "0.92.0"
meio-connect = "0.92.0"
metacrate = "0.1.2"
once_cell = "1.8.0"
rill-protocol = { version = "0.35.0", path = "../rill-protocol" }
serde = "1.0.126"
strum = { version = "0.21.0", features = ["derive"] }
thiserror = "1.0.26"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = "0.1.7"

[dev-dependencies]
ctrlc = "3.1.9"
env_logger = "0.9.0"
